### ISSUE TITLE
TC-1.00 ERROR

### ISSUE THREAD

**Issue by siennang** [thraxy/swe-project#3]
When a user searches for a result, they are not redirected to the results page.

**Comment by thraxy** [comment]
# Test Case Identifier: TC 1.00

Use Case Tested: UC -1

## Pass/Fail Critieria:
The test passes if the user is able to search using the search bar, is redirected to a results page, and is able to filter out the results.

## Input Data
Search data

| Test Procedure | Expected Results |
| ------------- | ------------- |
| **Step 1:** Type in search data  | The User is redirected to the results page. |
| **Step 2:** Type in incorrect data  | The user is not redirected to the results page. |
| **Step 3:** Filter out Results | The results are filtered out. |

# Still an Issue

User can not search

# Errors:

This is the error I received on search.html
```
Fatal error: Uncaught mysqli_sql_exception: Table 'parking_facilities_db.parking_facilities' doesn't exist in C:\xampp\htdocs\swe-project-main\swe-project-main\park\search.php:18 Stack trace: #0 C:\xampp\htdocs\swe-project-main\swe-project-main\park\search.php(18): mysqli_query(Object(mysqli), 'SELECT * FROM p...') #1 {main} thrown in C:\xampp\htdocs\swe-project-main\swe-project-main\park\search.php on line 18
```

This is the error I received on index.html
```
Warning: Undefined array key "submit" in C:\xampp\htdocs\swe-project-main\swe-project-main\park\search.php on line 11

Warning: Undefined array key "search" in C:\xampp\htdocs\swe-project-main\swe-project-main\park\search.php on line 12

Fatal error: Uncaught mysqli_sql_exception: Table 'parking_facilities_db.parking_facilities' doesn't exist in C:\xampp\htdocs\swe-project-main\swe-project-main\park\search.php:18 Stack trace: #0 C:\xampp\htdocs\swe-project-main\swe-project-main\park\search.php(18): mysqli_query(Object(mysqli), 'SELECT * FROM p...') #1 {main} thrown in C:\xampp\htdocs\swe-project-main\swe-project-main\park\search.php on line 18
```

## How I am approaching this problem
As mentioned in the other issues, the problem most likely is caused by the connection to the database. To approach this I will have to change/add code to the search.php file.
